# Generated by Django 5.0.2 on 2024-03-03 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id_etudiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom_etd', models.CharField(max_length=50)),
                ('prenom_etd', models.CharField(max_length=50)),
                ('etablissement_etd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'etudiants',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('chercheur_role', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id_publication', models.AutoField(primary_key=True, serialize=False)),
                ('acronyme', models.CharField(max_length=50)),
                ('descrp_acronyme', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('ptype', models.CharField(choices=[('Journaux', 'Journaux'), ('Conference', 'Conference'), ('Autre', 'Autre')], max_length=50)),
            ],
            options={
                'db_table': 'publications',
            },
        ),
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id_chercheur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_chercheur', models.CharField(max_length=50)),
                ('prenom_chercheur', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('date_naiss', models.DateField()),
                ('etablissement', models.CharField(max_length=50)),
                ('diplome', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=50)),
                ('dblp_lien', models.CharField(max_length=50)),
                ('bureau', models.CharField(max_length=50)),
                ('role_eq', models.CharField(max_length=50)),
                ('fonction_etbl', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('id_projet', models.ForeignKey(db_column='id_projet', null=True, on_delete=django.db.models.deletion.CASCADE, to='lmcs.projet')),
            ],
            options={
                'db_table': 'Chercheurs',
            },
        ),
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_encadrement', models.CharField(choices=[('PFE', 'PFE'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('Autre', 'Autre')], max_length=50)),
                ('intitule', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('id_chercheur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmcs.chercheur')),
                ('id_etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmcs.etudiants')),
            ],
            options={
                'db_table': 'encadrements',
                'unique_together': {('id_chercheur', 'id_etudiant')},
            },
        ),
        migrations.CreateModel(
            name='PubliePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('domaine', models.CharField(max_length=50)),
                ('prolongement_page', models.CharField(max_length=50)),
                ('ordre_chercheur', models.IntegerField(unique=True)),
                ('id_chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmcs.chercheur')),
                ('id_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmcs.publication')),
            ],
            options={
                'db_table': 'publie_publication',
                'unique_together': {('id_chercheur', 'id_publication')},
            },
        ),
    ]
