# Generated by Django 5.0.2 on 2024-03-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chercheur',
            name='grade_recherche',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chercheur',
            name='date_naiss',
            field=models.CharField(max_length=50),
        ),
    ]
